server:
  port: 8001
  servlet:
    context-path: /member

spring:
  #数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: train
    password: train
    url: jdbc:mysql://localhost/train?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
  application:
    name: member

#mybatis xml路径
mybatis:
  mapper-locations: classpath:/mapper/**/*xml

logging:
  level:
    com.study.train.member.mapper: trace