server:
  port: 8000
spring:
  cloud:
    gateway:
      routes:
        - id: member
          uri: http://127.0.0.1:8001
#          uri: lb://member
          predicates:
            - Path=/member/**
        - id: business
          uri: http://127.0.0.1:8002
#          uri: lb://business
          predicates:
            - Path=/business/**
        - id: batch
          uri: http://127.0.0.1:8003
#          uri: lb://batch
          predicates:
            - Path=/batch/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            allowedHeaders: '*'
            allowedMethods: '*'
            allowedOriginPatterns: '*'
            maxAge: 3600
