server:
  port: 8002
  servlet:
    context-path: /business

spring:
  #数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/train_business?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: train_business
    password: train_business
  application:
    name: business
  cache:
    type: redis
    redis:
      use-key-prefix: true
      key-prefix: train_cache_
      cache-null-values: false
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
#mybatis xml路径
mybatis:
  mapper-locations: classpath:/mapper/**/*xml

logging:
  level:
    com.study.train.business.mapper: trace